dist: xenial
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

before_install:
  - pip install --user cpp-coveralls

script:
  - export CC=gcc-9
  - export CXX=g++-9
  - cmake --version
  - $CC --version
  - $CXX --version
  - cmake . -DCOVERAGE=1 -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . -- -j2
  - ./bin/unittests

after_success:
  - ls -alh
  - coveralls --root - . -E ".*gtest.*" -E ".*CMakeFiles.*"
  - ls -alh