dist: xenial
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

script:
  - export CC=clang-7
  - export CXX=clang-7
  - cmake --version
  - $CC --version
  - $CXX --version
  - cmake . -DCOVERAGE=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-fprofile-instr-generate -fcoverage-mapping" -DCMAKE_CXX_FLAGS="-fprofile-instr-generate -fcoverage-mapping"
  - cmake --build . -- -j2
  - LLVM_PROFILE_FILE="unittests.profraw" ./bin/unittests

after_success:
  - ls -alh
  - coveralls --root - . -E ".*gtest.*" -E ".*CMakeFiles.*"
  - ls -alh