dist: xenial
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-9

before_install:
  - pip install --user cpp-coveralls

script:
  - export CC=clang-9
  - export CXX=clang-9
  - cmake --version
  - $CC --version
  - $CXX --version
  - cmake . -DCOVERAGE=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-fprofile-instr-generate -fcoverage-mapping" -DCMAKE_CXX_FLAGS="-fprofile-instr-generate -fcoverage-mapping"
  - cmake --build . -- -j2
  - LLVM_PROFILE_FILE="unittests.profraw" ./bin/unittests

after_success:
  - ls -alh
  - coveralls --root - . -E ".*gtest.*" -E ".*CMakeFiles.*"
  - ls -alh